### ISSUE TITLE
Permissions are too broad

### ISSUE THREAD

**Issue by BarbzYHOOL** [diliproshitha/TradingViewToMetaTrader#11]
"Access your data for all websites"
I've seen another addon requiring access only to a certain domain name
That should require only access to tradingview.com

**Comment by diliproshitha** [comment]
This add-on does not access your personal information. And the reason for setting the permissions this way is, that some other trading related websites are using Tradingview as their charting package. If the permissions are limited to tradinvgiew.com, then this plugin won't work on those websites.

**Comment by BarbzYHOOL** [comment]
but it's only for tradingview, isn't it?

**Comment by diliproshitha** [comment]
The extension can be used on any website that uses Tradingview as its charting provider.

**Comment by BarbzYHOOL** [comment]
ok interesting
