### ISSUE TITLE
Extension Returns 'null' When Fetching Data in Chrome v123.0.6312.87 on MacOS Sonoma

### ISSUE THREAD

**Issue by cmacha2** [diliproshitha/TradingViewToMetaTrader#13]
I am encountering an issue with the Neo Trader extension while running Chrome version 123.0.6312.87 on MacOS Sonoma version 14.4 (23E214). The extension's console.log is outputting null following the call to getTradeInfo(). It appears there may be an issue with script injection or the interaction with the chrome object, which is preventing the extension from functioning as intended.

Steps to Reproduce:

Install the Neo Trader extension in Chrome.
Open the Chrome developer console.
Attempt to execute the function that retrieves trading information from TradingView.
Observe that the console logs a null result.
Expected Behavior:
The function is supposed to fetch data from TradingView and return a populated object containing the trade information.

Actual Behavior:
Instead of retrieving data, the function returns null, indicating a potential problem with script injection or with the Chrome object's response. Attached screenshots demonstrate the console log output and the object returned by chrome.scripting.executeScript, which is unexpectedly null.

Additional Information:

Operating System: MacOS Sonoma version 14.4 (23E214)
Screenshots: [please attach your screenshots here]
<img width="1507" alt="Screenshot 2024-03-31 at 4 39 17 AM" src="https://github.com/diliproshitha/neo-trader/assets/61942599/0e5b7960-4e24-45f7-9d09-81d3449ff564">
<img width="1512" alt="Screenshot 2024-03-31 at 4 39 24 AM" src="https://github.com/diliproshitha/neo-trader/assets/61942599/c75376af-dd0a-474f-869a-f83b3fc88d19">

**Comment by diliproshitha** [comment]
Hi @cmacha2 
Can you re-install the extension and try again?

**Comment by cmacha2** [comment]
CONTINUE THE ISSUE

**Comment by diliproshitha** [comment]
Try updating the browser. It is working for me in Chrome v123.0.6312.106

**Comment by cmacha2** [comment]
It does it and it continues with the same thing. Coincidentally, I tried it on a laptop with Windows and it worked, it was working for two days and suddenly I reinstalled and it stopped working again. I passed it on to a friend and it's still the same, it doesn't load the trade information and it doesn't work. where the error comes

**Comment by cmacha2** [comment]
I found the problem. It was that my TradingVIew was setting in spanish for default and the extension didnt find the selectors. Thanks for replay and take the time.

**Comment by cmacha2** [comment]
Everyting find the problem was solve, Thanks for the help Diliproshitha
